/*
###############################################################
#  Generated by:      Cadence Encounter 14.13-s036_1
#  OS:                Linux x86_64(Host ID rhel-sal-03.ict.kth.se)
#  Generated on:      Tue Dec  1 16:30:01 2015
#  Design:            FIR_Toplevel_5
#  Command:           saveNetlist Phy_FIR.v
###############################################################
*/
module SRAM (
	rst_n, 
	rws, 
	addrs, 
	inp, 
	outp);
   input rst_n;
   input rws;
   input [2:0] addrs;
   input [3:0] inp;
   output [3:0] outp;

   // Internal wires
   wire \mem2[0][3] ;
   wire \mem2[0][2] ;
   wire \mem2[0][1] ;
   wire \mem2[0][0] ;
   wire \mem2[1][3] ;
   wire \mem2[1][2] ;
   wire \mem2[1][1] ;
   wire \mem2[1][0] ;
   wire \mem2[2][3] ;
   wire \mem2[2][2] ;
   wire \mem2[2][1] ;
   wire \mem2[2][0] ;
   wire \mem2[3][3] ;
   wire \mem2[3][2] ;
   wire \mem2[3][1] ;
   wire \mem2[3][0] ;
   wire \mem2[4][3] ;
   wire \mem2[4][2] ;
   wire \mem2[4][1] ;
   wire \mem2[4][0] ;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N43;
   wire N44;
   wire N45;
   wire N46;
   wire N47;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;

   LHD1 \mem2_reg[0][3]  (.Q(\mem2[0][3] ),
	.E(N42),
	.D(N38));
   LHD1 \mem2_reg[0][2]  (.Q(\mem2[0][2] ),
	.E(N42),
	.D(N37));
   LHD1 \mem2_reg[0][1]  (.Q(\mem2[0][1] ),
	.E(N42),
	.D(N36));
   LHD1 \mem2_reg[0][0]  (.Q(\mem2[0][0] ),
	.E(N42),
	.D(N35));
   LHD1 \mem2_reg[1][3]  (.Q(\mem2[1][3] ),
	.E(N41),
	.D(N38));
   LHD1 \mem2_reg[1][2]  (.Q(\mem2[1][2] ),
	.E(N41),
	.D(N37));
   LHD1 \mem2_reg[1][1]  (.Q(\mem2[1][1] ),
	.E(N41),
	.D(N36));
   LHD1 \mem2_reg[1][0]  (.Q(\mem2[1][0] ),
	.E(N41),
	.D(N35));
   LHD1 \mem2_reg[2][3]  (.Q(\mem2[2][3] ),
	.E(N40),
	.D(N38));
   LHD1 \mem2_reg[2][2]  (.Q(\mem2[2][2] ),
	.E(N40),
	.D(N37));
   LHD1 \mem2_reg[2][1]  (.Q(\mem2[2][1] ),
	.E(N40),
	.D(N36));
   LHD1 \mem2_reg[2][0]  (.Q(\mem2[2][0] ),
	.E(N40),
	.D(N35));
   LHD1 \mem2_reg[3][3]  (.Q(\mem2[3][3] ),
	.E(N39),
	.D(N38));
   LHD1 \mem2_reg[3][2]  (.Q(\mem2[3][2] ),
	.E(N39),
	.D(N37));
   LHD1 \mem2_reg[3][1]  (.Q(\mem2[3][1] ),
	.E(N39),
	.D(N36));
   LHD1 \mem2_reg[3][0]  (.Q(\mem2[3][0] ),
	.E(N39),
	.D(N35));
   LNCND1 \mem2_reg[4][3]  (.Q(\mem2[4][3] ),
	.EN(n23),
	.D(inp[3]),
	.CDN(rst_n));
   LNCND1 \mem2_reg[4][2]  (.Q(\mem2[4][2] ),
	.EN(n23),
	.D(inp[2]),
	.CDN(rst_n));
   LNCND1 \mem2_reg[4][1]  (.Q(\mem2[4][1] ),
	.EN(n23),
	.D(inp[1]),
	.CDN(rst_n));
   LNCND1 \mem2_reg[4][0]  (.Q(\mem2[4][0] ),
	.EN(n23),
	.D(inp[0]),
	.CDN(rst_n));
   LHD1 \outp_reg[3]  (.Q(outp[3]),
	.E(N43),
	.D(N47));
   LHD1 \outp_reg[2]  (.Q(outp[2]),
	.E(N43),
	.D(N46));
   LHD1 \outp_reg[1]  (.Q(outp[1]),
	.E(N43),
	.D(N45));
   LHD1 \outp_reg[0]  (.Q(outp[0]),
	.E(N43),
	.D(N44));
   INVD0 U3 (.ZN(n1),
	.I(rst_n));
   OAI21D0 U4 (.ZN(N41),
	.B(rst_n),
	.A2(n22),
	.A1(n7));
   OAI21D0 U5 (.ZN(N39),
	.B(rst_n),
	.A2(n22),
	.A1(n5));
   INVD1 U6 (.ZN(n5),
	.I(n12));
   NR2D1 U7 (.ZN(n12),
	.A2(n8),
	.A1(n6));
   OAI31D1 U8 (.ZN(N42),
	.B(rst_n),
	.A3(n12),
	.A2(n13),
	.A1(n21));
   ND3D1 U9 (.ZN(n21),
	.A3(n7),
	.A2(n2),
	.A1(n3));
   OAI21D0 U10 (.ZN(N40),
	.B(rst_n),
	.A2(n22),
	.A1(n4));
   INVD1 U11 (.ZN(n4),
	.I(n13));
   INVD1 U12 (.ZN(n7),
	.I(n11));
   ND2D1 U13 (.ZN(n22),
	.A2(n2),
	.A1(n3));
   ND2D1 U14 (.ZN(N43),
	.A2(n2),
	.A1(rst_n));
   NR2D1 U15 (.ZN(n13),
	.A2(addrs[0]),
	.A1(n6));
   NR2D1 U16 (.ZN(n11),
	.A2(addrs[1]),
	.A1(n8));
   NR3D0 U17 (.ZN(n14),
	.A3(addrs[0]),
	.A2(addrs[2]),
	.A1(addrs[1]));
   ND4D1 U18 (.ZN(n23),
	.A4(n2),
	.A3(n6),
	.A2(n8),
	.A1(addrs[2]));
   INVD1 U19 (.ZN(n2),
	.I(rws));
   INVD1 U20 (.ZN(n8),
	.I(addrs[0]));
   INVD1 U21 (.ZN(n6),
	.I(addrs[1]));
   AOI21D0 U22 (.ZN(N44),
	.B(n1),
	.A2(n20),
	.A1(n19));
   AOI22D0 U23 (.ZN(n19),
	.B2(addrs[2]),
	.B1(\mem2[4][0] ),
	.A2(n14),
	.A1(\mem2[0][0] ));
   AOI222D0 U24 (.ZN(n20),
	.C2(n13),
	.C1(\mem2[2][0] ),
	.B2(n12),
	.B1(\mem2[3][0] ),
	.A2(n11),
	.A1(\mem2[1][0] ));
   AOI21D0 U25 (.ZN(N45),
	.B(n1),
	.A2(n18),
	.A1(n17));
   AOI22D0 U26 (.ZN(n17),
	.B2(addrs[2]),
	.B1(\mem2[4][1] ),
	.A2(n14),
	.A1(\mem2[0][1] ));
   AOI222D0 U27 (.ZN(n18),
	.C2(n13),
	.C1(\mem2[2][1] ),
	.B2(n12),
	.B1(\mem2[3][1] ),
	.A2(n11),
	.A1(\mem2[1][1] ));
   AOI21D0 U28 (.ZN(N46),
	.B(n1),
	.A2(n16),
	.A1(n15));
   AOI22D0 U29 (.ZN(n15),
	.B2(addrs[2]),
	.B1(\mem2[4][2] ),
	.A2(n14),
	.A1(\mem2[0][2] ));
   AOI222D0 U30 (.ZN(n16),
	.C2(n13),
	.C1(\mem2[2][2] ),
	.B2(n12),
	.B1(\mem2[3][2] ),
	.A2(n11),
	.A1(\mem2[1][2] ));
   AOI21D0 U31 (.ZN(N47),
	.B(n1),
	.A2(n10),
	.A1(n9));
   AOI22D0 U32 (.ZN(n9),
	.B2(addrs[2]),
	.B1(\mem2[4][3] ),
	.A2(n14),
	.A1(\mem2[0][3] ));
   AOI222D0 U33 (.ZN(n10),
	.C2(n13),
	.C1(\mem2[2][3] ),
	.B2(n12),
	.B1(\mem2[3][3] ),
	.A2(n11),
	.A1(\mem2[1][3] ));
   INVD1 U34 (.ZN(n3),
	.I(addrs[2]));
   AN2D0 U35 (.Z(N35),
	.A2(rst_n),
	.A1(inp[0]));
   AN2D0 U36 (.Z(N36),
	.A2(rst_n),
	.A1(inp[1]));
   AN2D0 U37 (.Z(N37),
	.A2(rst_n),
	.A1(inp[2]));
   AN2D0 U38 (.Z(N38),
	.A2(rst_n),
	.A1(inp[3]));
endmodule

module SNPS_CLOCK_GATE_HIGH_Delayline_CB (
	CLK, 
	EN, 
	ENCLK, 
	clk__L4_N0);
   input CLK;
   input EN;
   output ENCLK;
   input clk__L4_N0;

   // Internal wires
   wire n_1;
   wire n;
   wire net83;
   wire net85;
   wire net86;
   wire net89;

   assign net86 = EN ;

   LND1 latch (.Q(net89),
	.EN(clk__L4_N0),
	.D(net86));
   AN2D1 main_gate (.Z(ENCLK),
	.A2(CLK),
	.A1(net89));
endmodule

module Delayline_CB_DW01_inc_0 (
	A, 
	SUM);
   input [31:0] A;
   output [31:0] SUM;

   // Internal wires
   wire [31:2] carry;

   CMPE22D1 U1_1_30 (.S(SUM[30]),
	.CO(carry[31]),
	.B(carry[30]),
	.A(A[30]));
   CMPE22D1 U1_1_27 (.S(SUM[27]),
	.CO(carry[28]),
	.B(carry[27]),
	.A(A[27]));
   CMPE22D1 U1_1_23 (.S(SUM[23]),
	.CO(carry[24]),
	.B(carry[23]),
	.A(A[23]));
   CMPE22D1 U1_1_16 (.S(SUM[16]),
	.CO(carry[17]),
	.B(carry[16]),
	.A(A[16]));
   CMPE22D1 U1_1_12 (.S(SUM[12]),
	.CO(carry[13]),
	.B(carry[12]),
	.A(A[12]));
   CMPE22D1 U1_1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.B(carry[6]),
	.A(A[6]));
   CMPE22D1 U1_1_29 (.S(SUM[29]),
	.CO(carry[30]),
	.B(carry[29]),
	.A(A[29]));
   CMPE22D1 U1_1_26 (.S(SUM[26]),
	.CO(carry[27]),
	.B(carry[26]),
	.A(A[26]));
   CMPE22D1 U1_1_25 (.S(SUM[25]),
	.CO(carry[26]),
	.B(carry[25]),
	.A(A[25]));
   CMPE22D1 U1_1_22 (.S(SUM[22]),
	.CO(carry[23]),
	.B(carry[22]),
	.A(A[22]));
   CMPE22D1 U1_1_21 (.S(SUM[21]),
	.CO(carry[22]),
	.B(carry[21]),
	.A(A[21]));
   CMPE22D1 U1_1_19 (.S(SUM[19]),
	.CO(carry[20]),
	.B(carry[19]),
	.A(A[19]));
   CMPE22D1 U1_1_18 (.S(SUM[18]),
	.CO(carry[19]),
	.B(carry[18]),
	.A(A[18]));
   CMPE22D1 U1_1_15 (.S(SUM[15]),
	.CO(carry[16]),
	.B(carry[15]),
	.A(A[15]));
   CMPE22D1 U1_1_14 (.S(SUM[14]),
	.CO(carry[15]),
	.B(carry[14]),
	.A(A[14]));
   CMPE22D1 U1_1_9 (.S(SUM[9]),
	.CO(carry[10]),
	.B(carry[9]),
	.A(A[9]));
   CMPE22D1 U1_1_8 (.S(SUM[8]),
	.CO(carry[9]),
	.B(carry[8]),
	.A(A[8]));
   CMPE22D1 U1_1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.B(carry[5]),
	.A(A[5]));
   CMPE22D1 U1_1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.B(carry[4]),
	.A(A[4]));
   CMPE22D1 U1_1_28 (.S(SUM[28]),
	.CO(carry[29]),
	.B(carry[28]),
	.A(A[28]));
   CMPE22D1 U1_1_24 (.S(SUM[24]),
	.CO(carry[25]),
	.B(carry[24]),
	.A(A[24]));
   CMPE22D1 U1_1_20 (.S(SUM[20]),
	.CO(carry[21]),
	.B(carry[20]),
	.A(A[20]));
   CMPE22D1 U1_1_17 (.S(SUM[17]),
	.CO(carry[18]),
	.B(carry[17]),
	.A(A[17]));
   CMPE22D1 U1_1_13 (.S(SUM[13]),
	.CO(carry[14]),
	.B(carry[13]),
	.A(A[13]));
   CMPE22D1 U1_1_7 (.S(SUM[7]),
	.CO(carry[8]),
	.B(carry[7]),
	.A(A[7]));
   CMPE22D1 U1_1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.B(carry[3]),
	.A(A[3]));
   CMPE22D1 U1_1_11 (.S(SUM[11]),
	.CO(carry[12]),
	.B(carry[11]),
	.A(A[11]));
   CMPE22D1 U1_1_10 (.S(SUM[10]),
	.CO(carry[11]),
	.B(carry[10]),
	.A(A[10]));
   CMPE22D1 U1_1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.B(carry[2]),
	.A(A[2]));
   CMPE22D1 U1_1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.B(A[0]),
	.A(A[1]));
   INVD1 U1 (.ZN(SUM[0]),
	.I(A[0]));
   CKXOR2D0 U2 (.Z(SUM[31]),
	.A2(A[31]),
	.A1(carry[31]));
endmodule

module Delayline_CB_DW01_dec_0 (
	A, 
	SUM);
   input [31:0] A;
   output [31:0] SUM;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;

   INVD1 U1 (.ZN(n4),
	.I(A[12]));
   INVD1 U2 (.ZN(n2),
	.I(A[8]));
   INVD1 U3 (.ZN(n3),
	.I(A[10]));
   INVD1 U4 (.ZN(n5),
	.I(A[27]));
   INVD1 U5 (.ZN(n6),
	.I(A[29]));
   INVD1 U6 (.ZN(SUM[0]),
	.I(A[0]));
   AO21D0 U7 (.Z(SUM[9]),
	.B(n8),
	.A2(A[9]),
	.A1(n7));
   OAI21D0 U8 (.ZN(SUM[8]),
	.B(n7),
	.A2(n2),
	.A1(n9));
   AO21D0 U9 (.Z(SUM[7]),
	.B(n9),
	.A2(A[7]),
	.A1(n10));
   IOA21D0 U10 (.ZN(SUM[6]),
	.B(n10),
	.A2(A[6]),
	.A1(n11));
   IOA21D0 U11 (.ZN(SUM[5]),
	.B(n11),
	.A2(A[5]),
	.A1(n12));
   IOA21D0 U12 (.ZN(SUM[4]),
	.B(n12),
	.A2(A[4]),
	.A1(n13));
   IOA21D0 U13 (.ZN(SUM[3]),
	.B(n13),
	.A2(A[3]),
	.A1(n14));
   CKXOR2D0 U14 (.Z(SUM[31]),
	.A2(n15),
	.A1(A[31]));
   NR2D0 U15 (.ZN(n15),
	.A2(n16),
	.A1(A[30]));
   XNR2D0 U16 (.ZN(SUM[30]),
	.A2(A[30]),
	.A1(n16));
   IOA21D0 U17 (.ZN(SUM[2]),
	.B(n14),
	.A2(A[2]),
	.A1(n17));
   OAI21D0 U18 (.ZN(SUM[29]),
	.B(n16),
	.A2(n6),
	.A1(n18));
   ND2D0 U19 (.ZN(n16),
	.A2(n6),
	.A1(n18));
   AO21D0 U20 (.Z(SUM[28]),
	.B(n18),
	.A2(A[28]),
	.A1(n19));
   NR2D0 U21 (.ZN(n18),
	.A2(A[28]),
	.A1(n19));
   OAI21D0 U22 (.ZN(SUM[27]),
	.B(n19),
	.A2(n5),
	.A1(n20));
   ND2D0 U23 (.ZN(n19),
	.A2(n5),
	.A1(n20));
   AO21D0 U24 (.Z(SUM[26]),
	.B(n20),
	.A2(A[26]),
	.A1(n21));
   NR2D0 U25 (.ZN(n20),
	.A2(A[26]),
	.A1(n21));
   IOA21D0 U26 (.ZN(SUM[25]),
	.B(n21),
	.A2(A[25]),
	.A1(n22));
   OR2D0 U27 (.Z(n21),
	.A2(A[25]),
	.A1(n22));
   IOA21D0 U28 (.ZN(SUM[24]),
	.B(n22),
	.A2(A[24]),
	.A1(n23));
   OR2D0 U29 (.Z(n22),
	.A2(A[24]),
	.A1(n23));
   IOA21D0 U30 (.ZN(SUM[23]),
	.B(n23),
	.A2(A[23]),
	.A1(n24));
   OR2D0 U31 (.Z(n23),
	.A2(A[23]),
	.A1(n24));
   IOA21D0 U32 (.ZN(SUM[22]),
	.B(n24),
	.A2(A[22]),
	.A1(n25));
   OR2D0 U33 (.Z(n24),
	.A2(A[22]),
	.A1(n25));
   IOA21D0 U34 (.ZN(SUM[21]),
	.B(n25),
	.A2(A[21]),
	.A1(n26));
   OR2D0 U35 (.Z(n25),
	.A2(A[21]),
	.A1(n26));
   IOA21D0 U36 (.ZN(SUM[20]),
	.B(n26),
	.A2(A[20]),
	.A1(n27));
   OR2D0 U37 (.Z(n26),
	.A2(A[20]),
	.A1(n27));
   IOA21D0 U38 (.ZN(SUM[1]),
	.B(n17),
	.A2(A[1]),
	.A1(A[0]));
   IOA21D0 U39 (.ZN(SUM[19]),
	.B(n27),
	.A2(A[19]),
	.A1(n28));
   OR2D0 U40 (.Z(n27),
	.A2(A[19]),
	.A1(n28));
   IOA21D0 U41 (.ZN(SUM[18]),
	.B(n28),
	.A2(A[18]),
	.A1(n29));
   OR2D0 U42 (.Z(n28),
	.A2(A[18]),
	.A1(n29));
   IOA21D0 U43 (.ZN(SUM[17]),
	.B(n29),
	.A2(A[17]),
	.A1(n30));
   OR2D0 U44 (.Z(n29),
	.A2(A[17]),
	.A1(n30));
   IOA21D0 U45 (.ZN(SUM[16]),
	.B(n30),
	.A2(A[16]),
	.A1(n31));
   OR2D0 U46 (.Z(n30),
	.A2(A[16]),
	.A1(n31));
   IOA21D0 U47 (.ZN(SUM[15]),
	.B(n31),
	.A2(A[15]),
	.A1(n32));
   OR2D0 U48 (.Z(n31),
	.A2(A[15]),
	.A1(n32));
   IOA21D0 U49 (.ZN(SUM[14]),
	.B(n32),
	.A2(A[14]),
	.A1(n33));
   OR2D0 U50 (.Z(n32),
	.A2(A[14]),
	.A1(n33));
   IOA21D0 U51 (.ZN(SUM[13]),
	.B(n33),
	.A2(A[13]),
	.A1(n34));
   OR2D0 U52 (.Z(n33),
	.A2(A[13]),
	.A1(n34));
   OAI21D0 U53 (.ZN(SUM[12]),
	.B(n34),
	.A2(n4),
	.A1(n35));
   ND2D0 U54 (.ZN(n34),
	.A2(n4),
	.A1(n35));
   AO21D0 U55 (.Z(SUM[11]),
	.B(n35),
	.A2(A[11]),
	.A1(n36));
   NR2D0 U56 (.ZN(n35),
	.A2(A[11]),
	.A1(n36));
   OAI21D0 U57 (.ZN(SUM[10]),
	.B(n36),
	.A2(n3),
	.A1(n8));
   ND2D0 U58 (.ZN(n36),
	.A2(n3),
	.A1(n8));
   NR2D0 U59 (.ZN(n8),
	.A2(A[9]),
	.A1(n7));
   ND2D0 U60 (.ZN(n7),
	.A2(n2),
	.A1(n9));
   NR2D0 U61 (.ZN(n9),
	.A2(A[7]),
	.A1(n10));
   OR2D0 U62 (.Z(n10),
	.A2(A[6]),
	.A1(n11));
   OR2D0 U63 (.Z(n11),
	.A2(A[5]),
	.A1(n12));
   OR2D0 U64 (.Z(n12),
	.A2(A[4]),
	.A1(n13));
   OR2D0 U65 (.Z(n13),
	.A2(A[3]),
	.A1(n14));
   OR2D0 U66 (.Z(n14),
	.A2(A[2]),
	.A1(n17));
   OR2D0 U67 (.Z(n17),
	.A2(A[0]),
	.A1(A[1]));
endmodule

module Delayline_CB (
	rst_n, 
	clk, 
	sample_clk, 
	sample, 
	sample_out, 
	clk__L4_N0, 
	clk__L4_N1, 
	clk__L4_N2);
   input rst_n;
   input clk;
   input sample_clk;
   input [3:0] sample;
   output [3:0] sample_out;
   input clk__L4_N0;
   input clk__L4_N1;
   input clk__L4_N2;

   // Internal wires
   wire net95__L1_N0;
   wire rws_wire;
   wire N9;
   wire N10;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N43;
   wire N44;
   wire N45;
   wire N46;
   wire N47;
   wire N48;
   wire N49;
   wire N50;
   wire N51;
   wire N52;
   wire N53;
   wire N54;
   wire N55;
   wire N56;
   wire N57;
   wire N58;
   wire N59;
   wire N60;
   wire N61;
   wire N62;
   wire N63;
   wire N64;
   wire N65;
   wire N66;
   wire N67;
   wire N68;
   wire N69;
   wire N70;
   wire N71;
   wire N72;
   wire N74;
   wire N75;
   wire N76;
   wire N77;
   wire N78;
   wire N79;
   wire N80;
   wire N81;
   wire N82;
   wire N83;
   wire N84;
   wire N85;
   wire N86;
   wire N87;
   wire N88;
   wire N89;
   wire N90;
   wire N91;
   wire N92;
   wire N93;
   wire N94;
   wire N95;
   wire N96;
   wire N97;
   wire N98;
   wire N99;
   wire N100;
   wire N101;
   wire N102;
   wire N103;
   wire N104;
   wire N105;
   wire N138;
   wire N139;
   wire N140;
   wire N141;
   wire N142;
   wire N143;
   wire N144;
   wire N145;
   wire N146;
   wire N147;
   wire N148;
   wire N149;
   wire N150;
   wire N151;
   wire N152;
   wire N153;
   wire N154;
   wire N155;
   wire N156;
   wire N157;
   wire N158;
   wire N159;
   wire N160;
   wire N161;
   wire N162;
   wire N163;
   wire N164;
   wire N165;
   wire N166;
   wire N167;
   wire N168;
   wire N169;
   wire N170;
   wire N171;
   wire N172;
   wire net95;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n1;
   wire n2;
   wire n24;
   wire n25;
   wire n29;
   wire [2:0] adrs_wire;
   wire [3:0] sample_write;
   wire [31:0] counter;
   wire [31:0] pointer;

   BUFFD12 net95__L1_I0 (.Z(net95__L1_N0),
	.I(net95));
   OR4D1 U37 (.Z(n8),
	.A4(pointer[27]),
	.A3(pointer[26]),
	.A2(pointer[25]),
	.A1(pointer[24]));
   OR4D1 U38 (.Z(n7),
	.A4(pointer[30]),
	.A3(pointer[2]),
	.A2(pointer[29]),
	.A1(pointer[28]));
   OR4D1 U39 (.Z(n6),
	.A4(pointer[5]),
	.A3(pointer[4]),
	.A2(pointer[3]),
	.A1(pointer[31]));
   OR4D1 U40 (.Z(n5),
	.A4(pointer[9]),
	.A3(pointer[8]),
	.A2(pointer[7]),
	.A1(pointer[6]));
   OR4D1 U42 (.Z(n12),
	.A4(pointer[12]),
	.A3(pointer[11]),
	.A2(pointer[10]),
	.A1(pointer[0]));
   OR4D1 U43 (.Z(n11),
	.A4(pointer[16]),
	.A3(pointer[15]),
	.A2(pointer[14]),
	.A1(pointer[13]));
   OR4D1 U44 (.Z(n10),
	.A4(pointer[1]),
	.A3(pointer[19]),
	.A2(pointer[18]),
	.A1(pointer[17]));
   OR4D1 U45 (.Z(n9),
	.A4(pointer[23]),
	.A3(pointer[22]),
	.A2(pointer[21]),
	.A1(pointer[20]));
   IAO21D1 U81 (.ZN(n13),
	.B(sample_clk),
	.A2(n15),
	.A1(n14));
   SRAM U30_CBRAM (.rst_n(rst_n),
	.rws(rws_wire),
	.addrs(adrs_wire),
	.inp(sample_write),
	.outp(sample_out));
   SNPS_CLOCK_GATE_HIGH_Delayline_CB clk_gate_pointer_reg (.CLK(clk),
	.EN(sample_clk),
	.ENCLK(net95),
	.clk__L4_N0(clk__L4_N0));
   Delayline_CB_DW01_inc_0 add_78 (.A({ counter[31],
		counter[30],
		counter[29],
		counter[28],
		counter[27],
		counter[26],
		counter[25],
		counter[24],
		counter[23],
		counter[22],
		counter[21],
		counter[20],
		counter[19],
		counter[18],
		counter[17],
		counter[16],
		counter[15],
		counter[14],
		counter[13],
		counter[12],
		counter[11],
		counter[10],
		counter[9],
		counter[8],
		counter[7],
		counter[6],
		counter[5],
		counter[4],
		counter[3],
		n2,
		n24,
		n25 }),
	.SUM({ N105,
		N104,
		N103,
		N102,
		N101,
		N100,
		N99,
		N98,
		N97,
		N96,
		N95,
		N94,
		N93,
		N92,
		N91,
		N90,
		N89,
		N88,
		N87,
		N86,
		N85,
		N84,
		N83,
		N82,
		N81,
		N80,
		N79,
		N78,
		N77,
		N76,
		N75,
		N74 }));
   Delayline_CB_DW01_dec_0 sub_67 (.A(pointer),
	.SUM({ N40,
		N39,
		N38,
		N37,
		N36,
		N35,
		N34,
		N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27,
		N26,
		N25,
		N24,
		N23,
		N22,
		N21,
		N20,
		N19,
		N18,
		N17,
		N16,
		N15,
		N14,
		N13,
		N12,
		N11,
		N10,
		N9 }));
   AN2D0 C7 (.Z(n25),
	.A2(n13),
	.A1(counter[0]));
   AN2D0 C6 (.Z(n24),
	.A2(n13),
	.A1(counter[1]));
   AN2D0 C5 (.Z(n2),
	.A2(n13),
	.A1(counter[2]));
   DFSND1 rws_wire_reg (.SDN(rst_n),
	.Q(rws_wire),
	.D(n29),
	.CP(clk__L4_N1));
   DFCNQD1 \sample_write_reg[3]  (.Q(sample_write[3]),
	.D(sample[3]),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \sample_write_reg[2]  (.Q(sample_write[2]),
	.D(sample[2]),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \sample_write_reg[1]  (.Q(sample_write[1]),
	.D(sample[1]),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \sample_write_reg[0]  (.Q(sample_write[0]),
	.D(sample[0]),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \adrs_wire_reg[0]  (.Q(adrs_wire[0]),
	.D(N170),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \adrs_wire_reg[1]  (.Q(adrs_wire[1]),
	.D(N171),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \adrs_wire_reg[2]  (.Q(adrs_wire[2]),
	.D(N172),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[31]  (.Q(pointer[31]),
	.D(N72),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[29]  (.Q(pointer[29]),
	.D(N70),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[27]  (.Q(pointer[27]),
	.D(N68),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[25]  (.Q(pointer[25]),
	.D(N66),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[26]  (.Q(pointer[26]),
	.D(N67),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[28]  (.Q(pointer[28]),
	.D(N69),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[30]  (.Q(pointer[30]),
	.D(N71),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[14]  (.Q(pointer[14]),
	.D(N55),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[15]  (.Q(pointer[15]),
	.D(N56),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[17]  (.Q(pointer[17]),
	.D(N58),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[18]  (.Q(pointer[18]),
	.D(N59),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[19]  (.Q(pointer[19]),
	.D(N60),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[20]  (.Q(pointer[20]),
	.D(N61),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[21]  (.Q(pointer[21]),
	.D(N62),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[22]  (.Q(pointer[22]),
	.D(N63),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[24]  (.Q(pointer[24]),
	.D(N65),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[16]  (.Q(pointer[16]),
	.D(N57),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[23]  (.Q(pointer[23]),
	.D(N64),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[31]  (.Q(counter[31]),
	.D(N169),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[2]  (.Q(counter[2]),
	.D(N140),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[1]  (.Q(counter[1]),
	.D(N139),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[8]  (.Q(pointer[8]),
	.D(N49),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[10]  (.Q(pointer[10]),
	.D(N51),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[6]  (.Q(counter[6]),
	.D(N144),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[12]  (.Q(counter[12]),
	.D(N150),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[16]  (.Q(counter[16]),
	.D(N154),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[23]  (.Q(counter[23]),
	.D(N161),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[27]  (.Q(counter[27]),
	.D(N165),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[12]  (.Q(pointer[12]),
	.D(N53),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[5]  (.Q(counter[5]),
	.D(N143),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[9]  (.Q(counter[9]),
	.D(N147),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[15]  (.Q(counter[15]),
	.D(N153),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[19]  (.Q(counter[19]),
	.D(N157),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[22]  (.Q(counter[22]),
	.D(N160),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[26]  (.Q(counter[26]),
	.D(N164),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[30]  (.Q(counter[30]),
	.D(N168),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[4]  (.Q(counter[4]),
	.D(N142),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[8]  (.Q(counter[8]),
	.D(N146),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[14]  (.Q(counter[14]),
	.D(N152),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[18]  (.Q(counter[18]),
	.D(N156),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[21]  (.Q(counter[21]),
	.D(N159),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[25]  (.Q(counter[25]),
	.D(N163),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[29]  (.Q(counter[29]),
	.D(N167),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[3]  (.Q(counter[3]),
	.D(N141),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[7]  (.Q(counter[7]),
	.D(N145),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[13]  (.Q(counter[13]),
	.D(N151),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[17]  (.Q(counter[17]),
	.D(N155),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[20]  (.Q(counter[20]),
	.D(N158),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[24]  (.Q(counter[24]),
	.D(N162),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[28]  (.Q(counter[28]),
	.D(N166),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[6]  (.Q(pointer[6]),
	.D(N47),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[13]  (.Q(pointer[13]),
	.D(N54),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[7]  (.Q(pointer[7]),
	.D(N48),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[11]  (.Q(pointer[11]),
	.D(N52),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[9]  (.Q(pointer[9]),
	.D(N50),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[0]  (.Q(counter[0]),
	.D(N138),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[10]  (.Q(counter[10]),
	.D(N148),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[11]  (.Q(counter[11]),
	.D(N149),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[3]  (.Q(pointer[3]),
	.D(N44),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[4]  (.Q(pointer[4]),
	.D(N45),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[5]  (.Q(pointer[5]),
	.D(N46),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[1]  (.Q(pointer[1]),
	.D(N42),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[2]  (.Q(pointer[2]),
	.D(N43),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   DFCNQD1 \pointer_reg[0]  (.Q(pointer[0]),
	.D(N41),
	.CP(net95__L1_N0),
	.CDN(rst_n));
   ND2D1 U4 (.ZN(n1),
	.A2(n4),
	.A1(n3));
   AN2D0 U7 (.Z(N70),
	.A2(n1),
	.A1(N38));
   AN2D0 U8 (.Z(N68),
	.A2(n1),
	.A1(N36));
   ND4D1 U9 (.ZN(n14),
	.A4(n23),
	.A3(n22),
	.A2(n21),
	.A1(n20));
   ND4D1 U10 (.ZN(n15),
	.A4(n19),
	.A3(n18),
	.A2(n17),
	.A1(n16));
   AN2D0 U11 (.Z(N53),
	.A2(n1),
	.A1(N21));
   AN2D0 U12 (.Z(N51),
	.A2(n1),
	.A1(N19));
   AN2D0 U13 (.Z(N49),
	.A2(n1),
	.A1(N17));
   NR4D0 U14 (.ZN(n4),
	.A4(n8),
	.A3(n7),
	.A2(n6),
	.A1(n5));
   NR4D0 U15 (.ZN(n3),
	.A4(n12),
	.A3(n11),
	.A2(n10),
	.A1(n9));
   AN2D0 U16 (.Z(N72),
	.A2(n1),
	.A1(N40));
   AN2D0 U17 (.Z(N71),
	.A2(n1),
	.A1(N39));
   AN2D0 U18 (.Z(N69),
	.A2(n1),
	.A1(N37));
   NR4D0 U19 (.ZN(n20),
	.A4(counter[23]),
	.A3(counter[24]),
	.A2(counter[25]),
	.A1(counter[26]));
   NR4D0 U20 (.ZN(n19),
	.A4(counter[1]),
	.A3(counter[20]),
	.A2(counter[21]),
	.A1(counter[22]));
   NR4D0 U21 (.ZN(n18),
	.A4(counter[16]),
	.A3(counter[17]),
	.A2(counter[18]),
	.A1(counter[19]));
   NR4D0 U22 (.ZN(n23),
	.A4(counter[6]),
	.A3(counter[7]),
	.A2(counter[8]),
	.A1(counter[9]));
   NR4D0 U23 (.ZN(n22),
	.A4(counter[31]),
	.A3(counter[3]),
	.A2(counter[4]),
	.A1(counter[5]));
   NR4D0 U24 (.ZN(n17),
	.A4(counter[12]),
	.A3(counter[13]),
	.A2(counter[14]),
	.A1(counter[15]));
   NR4D0 U25 (.ZN(n21),
	.A4(counter[27]),
	.A3(counter[28]),
	.A2(counter[29]),
	.A1(counter[30]));
   INR4D0 U26 (.ZN(n16),
	.B3(counter[0]),
	.B2(counter[10]),
	.B1(counter[11]),
	.A1(counter[2]));
   AO22D0 U27 (.Z(N169),
	.B2(n13),
	.B1(N105),
	.A2(pointer[31]),
	.A1(sample_clk));
   AO22D0 U28 (.Z(N168),
	.B2(n13),
	.B1(N104),
	.A2(pointer[30]),
	.A1(sample_clk));
   AO22D0 U29 (.Z(N167),
	.B2(n13),
	.B1(N103),
	.A2(pointer[29]),
	.A1(sample_clk));
   AO22D0 U30 (.Z(N166),
	.B2(n13),
	.B1(N102),
	.A2(pointer[28]),
	.A1(sample_clk));
   AO22D0 U31 (.Z(N165),
	.B2(n13),
	.B1(N101),
	.A2(pointer[27]),
	.A1(sample_clk));
   AO22D0 U32 (.Z(N164),
	.B2(n13),
	.B1(N100),
	.A2(pointer[26]),
	.A1(sample_clk));
   AO22D0 U33 (.Z(N163),
	.B2(n13),
	.B1(N99),
	.A2(pointer[25]),
	.A1(sample_clk));
   AO22D0 U34 (.Z(N162),
	.B2(n13),
	.B1(N98),
	.A2(pointer[24]),
	.A1(sample_clk));
   AO22D0 U35 (.Z(N161),
	.B2(n13),
	.B1(N97),
	.A2(pointer[23]),
	.A1(sample_clk));
   AO22D0 U36 (.Z(N160),
	.B2(n13),
	.B1(N96),
	.A2(pointer[22]),
	.A1(sample_clk));
   AN2D0 U41 (.Z(N67),
	.A2(n1),
	.A1(N35));
   AN2D0 U46 (.Z(N66),
	.A2(n1),
	.A1(N34));
   AN2D0 U47 (.Z(N65),
	.A2(n1),
	.A1(N33));
   AN2D0 U48 (.Z(N64),
	.A2(n1),
	.A1(N32));
   AN2D0 U49 (.Z(N63),
	.A2(n1),
	.A1(N31));
   AN2D0 U50 (.Z(N62),
	.A2(n1),
	.A1(N30));
   AN2D0 U51 (.Z(N61),
	.A2(n1),
	.A1(N29));
   AN2D0 U52 (.Z(N60),
	.A2(n1),
	.A1(N28));
   AN2D0 U53 (.Z(N59),
	.A2(n1),
	.A1(N27));
   AN2D0 U54 (.Z(N58),
	.A2(n1),
	.A1(N26));
   AN2D0 U55 (.Z(N52),
	.A2(n1),
	.A1(N20));
   AO22D0 U56 (.Z(N159),
	.B2(n13),
	.B1(N95),
	.A2(pointer[21]),
	.A1(sample_clk));
   AO22D0 U57 (.Z(N158),
	.B2(n13),
	.B1(N94),
	.A2(pointer[20]),
	.A1(sample_clk));
   AO22D0 U58 (.Z(N157),
	.B2(n13),
	.B1(N93),
	.A2(pointer[19]),
	.A1(sample_clk));
   AO22D0 U59 (.Z(N156),
	.B2(n13),
	.B1(N92),
	.A2(pointer[18]),
	.A1(sample_clk));
   AO22D0 U60 (.Z(N155),
	.B2(n13),
	.B1(N91),
	.A2(pointer[17]),
	.A1(sample_clk));
   AO22D0 U61 (.Z(N154),
	.B2(n13),
	.B1(N90),
	.A2(pointer[16]),
	.A1(sample_clk));
   AO22D0 U62 (.Z(N153),
	.B2(n13),
	.B1(N89),
	.A2(pointer[15]),
	.A1(sample_clk));
   AO22D0 U63 (.Z(N152),
	.B2(n13),
	.B1(N88),
	.A2(pointer[14]),
	.A1(sample_clk));
   AO22D0 U64 (.Z(N151),
	.B2(n13),
	.B1(N87),
	.A2(pointer[13]),
	.A1(sample_clk));
   AO22D0 U65 (.Z(N150),
	.B2(n13),
	.B1(N86),
	.A2(pointer[12]),
	.A1(sample_clk));
   AO22D0 U66 (.Z(N149),
	.B2(n13),
	.B1(N85),
	.A2(pointer[11]),
	.A1(sample_clk));
   AO22D0 U67 (.Z(N148),
	.B2(n13),
	.B1(N84),
	.A2(pointer[10]),
	.A1(sample_clk));
   AO22D0 U68 (.Z(N147),
	.B2(n13),
	.B1(N83),
	.A2(pointer[9]),
	.A1(sample_clk));
   AO22D0 U69 (.Z(N146),
	.B2(n13),
	.B1(N82),
	.A2(pointer[8]),
	.A1(sample_clk));
   AO22D0 U70 (.Z(N145),
	.B2(n13),
	.B1(N81),
	.A2(pointer[7]),
	.A1(sample_clk));
   AO22D0 U71 (.Z(N144),
	.B2(n13),
	.B1(N80),
	.A2(pointer[6]),
	.A1(sample_clk));
   AO22D0 U72 (.Z(N143),
	.B2(n13),
	.B1(N79),
	.A2(pointer[5]),
	.A1(sample_clk));
   AO22D0 U73 (.Z(N142),
	.B2(n13),
	.B1(N78),
	.A2(pointer[4]),
	.A1(sample_clk));
   AO22D0 U74 (.Z(N141),
	.B2(n13),
	.B1(N77),
	.A2(pointer[3]),
	.A1(sample_clk));
   AO22D0 U75 (.Z(N140),
	.B2(n13),
	.B1(N76),
	.A2(pointer[2]),
	.A1(sample_clk));
   AN2D0 U76 (.Z(N57),
	.A2(n1),
	.A1(N25));
   AN2D0 U77 (.Z(N56),
	.A2(n1),
	.A1(N24));
   AN2D0 U78 (.Z(N55),
	.A2(n1),
	.A1(N23));
   AN2D0 U79 (.Z(N54),
	.A2(n1),
	.A1(N22));
   AN2D0 U80 (.Z(N50),
	.A2(n1),
	.A1(N18));
   AO22D0 U82 (.Z(N138),
	.B2(n13),
	.B1(N74),
	.A2(pointer[0]),
	.A1(sample_clk));
   AO22D0 U83 (.Z(N170),
	.B2(counter[0]),
	.B1(n29),
	.A2(pointer[0]),
	.A1(sample_clk));
   AO22D0 U84 (.Z(N139),
	.B2(n13),
	.B1(N75),
	.A2(pointer[1]),
	.A1(sample_clk));
   AO22D0 U85 (.Z(N172),
	.B2(counter[2]),
	.B1(n29),
	.A2(pointer[2]),
	.A1(sample_clk));
   AO22D0 U86 (.Z(N171),
	.B2(counter[1]),
	.B1(n29),
	.A2(pointer[1]),
	.A1(sample_clk));
   IND2D1 U87 (.ZN(N43),
	.B1(n1),
	.A1(N11));
   AN2D0 U88 (.Z(N41),
	.A2(n1),
	.A1(N9));
   AN2D0 U89 (.Z(N48),
	.A2(n1),
	.A1(N16));
   AN2D0 U90 (.Z(N47),
	.A2(n1),
	.A1(N15));
   AN2D0 U91 (.Z(N46),
	.A2(n1),
	.A1(N14));
   AN2D0 U92 (.Z(N45),
	.A2(n1),
	.A1(N13));
   AN2D0 U93 (.Z(N44),
	.A2(n1),
	.A1(N12));
   AN2D0 U94 (.Z(N42),
	.A2(n1),
	.A1(N10));
   INVD1 U95 (.ZN(n29),
	.I(sample_clk));
endmodule

module SNPS_CLOCK_GATE_HIGH_FIR_Processor (
	CLK, 
	EN, 
	ENCLK, 
	clk__L4_N1);
   input CLK;
   input EN;
   output ENCLK;
   input clk__L4_N1;

   // Internal wires
   wire n;
   wire net68;
   wire net70;
   wire net71;
   wire net74;

   assign ENCLK = net70 ;
   assign net71 = EN ;

   LND1 latch (.Q(net74),
	.EN(clk__L4_N1),
	.D(net71));
   AN2D0 main_gate (.Z(net70),
	.A2(CLK),
	.A1(net74));
endmodule

module FIR_Processor_DW01_dec_0 (
	A, 
	SUM);
   input [31:0] A;
   output [31:0] SUM;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;

   INVD1 U1 (.ZN(SUM[0]),
	.I(A[0]));
   INVD1 U2 (.ZN(n4),
	.I(A[12]));
   INVD1 U3 (.ZN(n3),
	.I(A[10]));
   INVD1 U4 (.ZN(n2),
	.I(A[8]));
   INVD1 U5 (.ZN(n6),
	.I(A[29]));
   INVD1 U6 (.ZN(n5),
	.I(A[27]));
   AO21D0 U7 (.Z(SUM[9]),
	.B(n8),
	.A2(A[9]),
	.A1(n7));
   OAI21D0 U8 (.ZN(SUM[8]),
	.B(n7),
	.A2(n2),
	.A1(n9));
   AO21D0 U9 (.Z(SUM[7]),
	.B(n9),
	.A2(A[7]),
	.A1(n10));
   IOA21D0 U10 (.ZN(SUM[6]),
	.B(n10),
	.A2(A[6]),
	.A1(n11));
   IOA21D0 U11 (.ZN(SUM[5]),
	.B(n11),
	.A2(A[5]),
	.A1(n12));
   IOA21D0 U12 (.ZN(SUM[4]),
	.B(n12),
	.A2(A[4]),
	.A1(n13));
   IOA21D0 U13 (.ZN(SUM[3]),
	.B(n13),
	.A2(A[3]),
	.A1(n14));
   CKXOR2D0 U14 (.Z(SUM[31]),
	.A2(n15),
	.A1(A[31]));
   NR2D0 U15 (.ZN(n15),
	.A2(n16),
	.A1(A[30]));
   XNR2D0 U16 (.ZN(SUM[30]),
	.A2(A[30]),
	.A1(n16));
   IOA21D0 U17 (.ZN(SUM[2]),
	.B(n14),
	.A2(A[2]),
	.A1(n17));
   OAI21D0 U18 (.ZN(SUM[29]),
	.B(n16),
	.A2(n6),
	.A1(n18));
   ND2D0 U19 (.ZN(n16),
	.A2(n6),
	.A1(n18));
   AO21D0 U20 (.Z(SUM[28]),
	.B(n18),
	.A2(A[28]),
	.A1(n19));
   NR2D0 U21 (.ZN(n18),
	.A2(A[28]),
	.A1(n19));
   OAI21D0 U22 (.ZN(SUM[27]),
	.B(n19),
	.A2(n5),
	.A1(n20));
   ND2D0 U23 (.ZN(n19),
	.A2(n5),
	.A1(n20));
   AO21D0 U24 (.Z(SUM[26]),
	.B(n20),
	.A2(A[26]),
	.A1(n21));
   NR2D0 U25 (.ZN(n20),
	.A2(A[26]),
	.A1(n21));
   IOA21D0 U26 (.ZN(SUM[25]),
	.B(n21),
	.A2(A[25]),
	.A1(n22));
   OR2D0 U27 (.Z(n21),
	.A2(A[25]),
	.A1(n22));
   IOA21D0 U28 (.ZN(SUM[24]),
	.B(n22),
	.A2(A[24]),
	.A1(n23));
   OR2D0 U29 (.Z(n22),
	.A2(A[24]),
	.A1(n23));
   IOA21D0 U30 (.ZN(SUM[23]),
	.B(n23),
	.A2(A[23]),
	.A1(n24));
   OR2D0 U31 (.Z(n23),
	.A2(A[23]),
	.A1(n24));
   IOA21D0 U32 (.ZN(SUM[22]),
	.B(n24),
	.A2(A[22]),
	.A1(n25));
   OR2D0 U33 (.Z(n24),
	.A2(A[22]),
	.A1(n25));
   IOA21D0 U34 (.ZN(SUM[21]),
	.B(n25),
	.A2(A[21]),
	.A1(n26));
   OR2D0 U35 (.Z(n25),
	.A2(A[21]),
	.A1(n26));
   IOA21D0 U36 (.ZN(SUM[20]),
	.B(n26),
	.A2(A[20]),
	.A1(n27));
   OR2D0 U37 (.Z(n26),
	.A2(A[20]),
	.A1(n27));
   IOA21D0 U38 (.ZN(SUM[1]),
	.B(n17),
	.A2(A[1]),
	.A1(A[0]));
   IOA21D0 U39 (.ZN(SUM[19]),
	.B(n27),
	.A2(A[19]),
	.A1(n28));
   OR2D0 U40 (.Z(n27),
	.A2(A[19]),
	.A1(n28));
   IOA21D0 U41 (.ZN(SUM[18]),
	.B(n28),
	.A2(A[18]),
	.A1(n29));
   OR2D0 U42 (.Z(n28),
	.A2(A[18]),
	.A1(n29));
   IOA21D0 U43 (.ZN(SUM[17]),
	.B(n29),
	.A2(A[17]),
	.A1(n30));
   OR2D0 U44 (.Z(n29),
	.A2(A[17]),
	.A1(n30));
   IOA21D0 U45 (.ZN(SUM[16]),
	.B(n30),
	.A2(A[16]),
	.A1(n31));
   OR2D0 U46 (.Z(n30),
	.A2(A[16]),
	.A1(n31));
   IOA21D0 U47 (.ZN(SUM[15]),
	.B(n31),
	.A2(A[15]),
	.A1(n32));
   OR2D0 U48 (.Z(n31),
	.A2(A[15]),
	.A1(n32));
   IOA21D0 U49 (.ZN(SUM[14]),
	.B(n32),
	.A2(A[14]),
	.A1(n33));
   OR2D0 U50 (.Z(n32),
	.A2(A[14]),
	.A1(n33));
   IOA21D0 U51 (.ZN(SUM[13]),
	.B(n33),
	.A2(A[13]),
	.A1(n34));
   OR2D0 U52 (.Z(n33),
	.A2(A[13]),
	.A1(n34));
   OAI21D0 U53 (.ZN(SUM[12]),
	.B(n34),
	.A2(n4),
	.A1(n35));
   ND2D0 U54 (.ZN(n34),
	.A2(n4),
	.A1(n35));
   AO21D0 U55 (.Z(SUM[11]),
	.B(n35),
	.A2(A[11]),
	.A1(n36));
   NR2D0 U56 (.ZN(n35),
	.A2(A[11]),
	.A1(n36));
   OAI21D0 U57 (.ZN(SUM[10]),
	.B(n36),
	.A2(n3),
	.A1(n8));
   ND2D0 U58 (.ZN(n36),
	.A2(n3),
	.A1(n8));
   NR2D0 U59 (.ZN(n8),
	.A2(A[9]),
	.A1(n7));
   ND2D0 U60 (.ZN(n7),
	.A2(n2),
	.A1(n9));
   NR2D0 U61 (.ZN(n9),
	.A2(A[7]),
	.A1(n10));
   OR2D0 U62 (.Z(n10),
	.A2(A[6]),
	.A1(n11));
   OR2D0 U63 (.Z(n11),
	.A2(A[5]),
	.A1(n12));
   OR2D0 U64 (.Z(n12),
	.A2(A[4]),
	.A1(n13));
   OR2D0 U65 (.Z(n13),
	.A2(A[3]),
	.A1(n14));
   OR2D0 U66 (.Z(n14),
	.A2(A[2]),
	.A1(n17));
   OR2D0 U67 (.Z(n17),
	.A2(A[0]),
	.A1(A[1]));
endmodule

module FIR_Processor_DW_mult_uns_0 (
	a, 
	b, 
	product);
   input [3:0] a;
   input [3:0] b;
   output [7:0] product;

   // Internal wires
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;

   CMPE32D1 U2 (.S(product[6]),
	.CO(product[7]),
	.CI(n2),
	.B(n7),
	.A(n19));
   CMPE32D1 U3 (.S(product[5]),
	.CO(n2),
	.CI(n3),
	.B(n9),
	.A(n8));
   CMPE32D1 U4 (.S(product[4]),
	.CO(n3),
	.CI(n4),
	.B(n10),
	.A(n13));
   CMPE32D1 U5 (.S(product[3]),
	.CO(n4),
	.CI(n5),
	.B(n14),
	.A(n16));
   CMPE32D1 U6 (.S(product[2]),
	.CO(n5),
	.CI(n18),
	.B(n6),
	.A(n26));
   CMPE22D1 U7 (.S(product[1]),
	.CO(n6),
	.B(n33),
	.A(n30));
   CMPE32D1 U8 (.S(n8),
	.CO(n7),
	.CI(n11),
	.B(n20),
	.A(n23));
   CMPE32D1 U9 (.S(n10),
	.CO(n9),
	.CI(n12),
	.B(n15),
	.A(n24));
   CMPE22D1 U10 (.S(n12),
	.CO(n11),
	.B(n21),
	.A(n27));
   CMPE32D1 U11 (.S(n14),
	.CO(n13),
	.CI(n17),
	.B(n28),
	.A(n31));
   CMPE22D1 U12 (.S(n16),
	.CO(n15),
	.B(n22),
	.A(n25));
   CMPE22D1 U13 (.S(n18),
	.CO(n17),
	.B(n29),
	.A(n32));
   INVD1 U40 (.ZN(n67),
	.I(b[1]));
   INVD1 U41 (.ZN(n66),
	.I(b[2]));
   INVD1 U42 (.ZN(n69),
	.I(b[3]));
   INVD1 U43 (.ZN(n68),
	.I(b[0]));
   INVD1 U44 (.ZN(n65),
	.I(a[0]));
   INVD1 U45 (.ZN(n64),
	.I(a[1]));
   INVD1 U46 (.ZN(n63),
	.I(a[2]));
   INVD1 U47 (.ZN(n62),
	.I(a[3]));
   NR2D0 U48 (.ZN(product[0]),
	.A2(n68),
	.A1(n65));
   NR2D0 U49 (.ZN(n33),
	.A2(n67),
	.A1(n65));
   NR2D0 U50 (.ZN(n32),
	.A2(n66),
	.A1(n65));
   NR2D0 U51 (.ZN(n31),
	.A2(n69),
	.A1(n65));
   NR2D0 U52 (.ZN(n30),
	.A2(n64),
	.A1(n68));
   NR2D0 U53 (.ZN(n29),
	.A2(n64),
	.A1(n67));
   NR2D0 U54 (.ZN(n28),
	.A2(n64),
	.A1(n66));
   NR2D0 U55 (.ZN(n27),
	.A2(n64),
	.A1(n69));
   NR2D0 U56 (.ZN(n26),
	.A2(n63),
	.A1(n68));
   NR2D0 U57 (.ZN(n25),
	.A2(n63),
	.A1(n67));
   NR2D0 U58 (.ZN(n24),
	.A2(n63),
	.A1(n66));
   NR2D0 U59 (.ZN(n23),
	.A2(n63),
	.A1(n69));
   NR2D0 U60 (.ZN(n22),
	.A2(n62),
	.A1(n68));
   NR2D0 U61 (.ZN(n21),
	.A2(n62),
	.A1(n67));
   NR2D0 U62 (.ZN(n20),
	.A2(n62),
	.A1(n66));
   NR2D0 U63 (.ZN(n19),
	.A2(n62),
	.A1(n69));
endmodule

module FIR_Processor_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO);
   input [7:0] A;
   input [7:0] B;
   input CI;
   output [7:0] SUM;
   output CO;

   // Internal wires
   wire n1;
   wire [7:1] carry;

   CMPE32D1 U1_6 (.S(SUM[6]),
	.CO(carry[7]),
	.CI(carry[6]),
	.B(B[6]),
	.A(A[6]));
   CMPE32D1 U1_5 (.S(SUM[5]),
	.CO(carry[6]),
	.CI(carry[5]),
	.B(B[5]),
	.A(A[5]));
   CMPE32D1 U1_4 (.S(SUM[4]),
	.CO(carry[5]),
	.CI(carry[4]),
	.B(B[4]),
	.A(A[4]));
   CMPE32D1 U1_3 (.S(SUM[3]),
	.CO(carry[4]),
	.CI(carry[3]),
	.B(B[3]),
	.A(A[3]));
   CMPE32D1 U1_2 (.S(SUM[2]),
	.CO(carry[3]),
	.CI(carry[2]),
	.B(B[2]),
	.A(A[2]));
   CMPE32D1 U1_1 (.S(SUM[1]),
	.CO(carry[2]),
	.CI(n1),
	.B(B[1]),
	.A(A[1]));
   XOR3D1 U1_7 (.Z(SUM[7]),
	.A3(carry[7]),
	.A2(B[7]),
	.A1(A[7]));
   XOR2D1 U1 (.Z(SUM[0]),
	.A2(A[0]),
	.A1(B[0]));
   AN2D0 U2 (.Z(n1),
	.A2(A[0]),
	.A1(B[0]));
endmodule

module FIR_Processor (
	rst_n, 
	clk, 
	sample_clk, 
	sample_delay_in, 
	coeficient, 
	coef_addr, 
	dav, 
	outp, 
	clk__L4_N0, 
	clk__L4_N1, 
	clk__L4_N2, 
	clk__L4_N3);
   input rst_n;
   input clk;
   input sample_clk;
   input [3:0] sample_delay_in;
   input [3:0] coeficient;
   output [2:0] coef_addr;
   output dav;
   output [3:0] outp;
   input clk__L4_N0;
   input clk__L4_N1;
   input clk__L4_N2;
   input clk__L4_N3;

   // Internal wires
   wire CURRENT_STATE;
   wire NEXT_STATE;
   wire N9;
   wire N10;
   wire N11;
   wire N12;
   wire N13;
   wire N14;
   wire N15;
   wire N16;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire N25;
   wire N26;
   wire N27;
   wire N28;
   wire N29;
   wire N30;
   wire N31;
   wire N32;
   wire N33;
   wire N34;
   wire N35;
   wire N36;
   wire N37;
   wire N38;
   wire N39;
   wire N40;
   wire N41;
   wire N42;
   wire N43;
   wire N44;
   wire N45;
   wire N46;
   wire N47;
   wire N48;
   wire N49;
   wire N50;
   wire N51;
   wire N52;
   wire N53;
   wire N54;
   wire N55;
   wire N56;
   wire N57;
   wire N58;
   wire N59;
   wire N60;
   wire N61;
   wire N62;
   wire N63;
   wire N64;
   wire N65;
   wire N66;
   wire N67;
   wire N68;
   wire N69;
   wire N70;
   wire N71;
   wire N72;
   wire N85;
   wire N86;
   wire N87;
   wire N88;
   wire N89;
   wire N90;
   wire N91;
   wire N92;
   wire N104;
   wire N105;
   wire N106;
   wire N107;
   wire N108;
   wire N109;
   wire N110;
   wire N111;
   wire N112;
   wire N113;
   wire N114;
   wire net80;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire N84;
   wire N83;
   wire N82;
   wire N81;
   wire N80;
   wire N79;
   wire N78;
   wire N77;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n17;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n68;
   wire n71;
   wire n72;
   wire n73;
   wire [31:0] counter;
   wire [7:0] accumulator;

   IAO21D1 U39 (.ZN(n9),
	.B(N112),
	.A2(coef_addr[1]),
	.A1(n71));
   SNPS_CLOCK_GATE_HIGH_FIR_Processor clk_gate_outp_wire_reg (.CLK(clk),
	.EN(n72),
	.ENCLK(net80),
	.clk__L4_N1(clk__L4_N1));
   FIR_Processor_DW01_dec_0 sub_79 (.A({ n4,
		n5,
		n6,
		n17,
		n22,
		n23,
		n24,
		n25,
		n26,
		n27,
		n28,
		n29,
		n30,
		n31,
		n32,
		n33,
		n34,
		n35,
		n36,
		n37,
		n38,
		n39,
		n40,
		n41,
		n42,
		n43,
		n44,
		n45,
		n46,
		n47,
		n48,
		n49 }),
	.SUM({ N40,
		N39,
		N38,
		N37,
		N36,
		N35,
		N34,
		N33,
		N32,
		N31,
		N30,
		N29,
		N28,
		N27,
		N26,
		N25,
		N24,
		N23,
		N22,
		N21,
		N20,
		N19,
		N18,
		N17,
		N16,
		N15,
		N14,
		N13,
		N12,
		N11,
		N10,
		N9 }));
   FIR_Processor_DW_mult_uns_0 mult_115 (.a({ n59,
		n60,
		n61,
		n62 }),
	.b({ n63,
		n64,
		n65,
		n66 }),
	.product({ N84,
		N83,
		N82,
		N81,
		N80,
		N79,
		N78,
		N77 }));
   FIR_Processor_DW01_add_0 add_115 (.A({ N84,
		N83,
		N82,
		N81,
		N80,
		N79,
		N78,
		N77 }),
	.B({ n51,
		n52,
		n53,
		n54,
		n55,
		n56,
		n57,
		n58 }),
	.CI(1'b0),
	.SUM({ N92,
		N91,
		N90,
		N89,
		N88,
		N87,
		N86,
		N85 }));
   OR2D0 C23 (.Z(n66),
	.A2(n71),
	.A1(coeficient[0]));
   AN2D0 C22 (.Z(n65),
	.A2(n11),
	.A1(coeficient[1]));
   AN2D0 C21 (.Z(n64),
	.A2(n11),
	.A1(coeficient[2]));
   AN2D0 C20 (.Z(n63),
	.A2(n11),
	.A1(coeficient[3]));
   AN2D0 C19 (.Z(n62),
	.A2(n11),
	.A1(sample_delay_in[0]));
   AN2D0 C18 (.Z(n61),
	.A2(n11),
	.A1(sample_delay_in[1]));
   AN2D0 C17 (.Z(n60),
	.A2(n11),
	.A1(sample_delay_in[2]));
   AN2D0 C16 (.Z(n59),
	.A2(n11),
	.A1(sample_delay_in[3]));
   AN2D0 C65 (.Z(n58),
	.A2(n11),
	.A1(accumulator[0]));
   AN2D0 C64 (.Z(n57),
	.A2(n11),
	.A1(accumulator[1]));
   AN2D0 C63 (.Z(n56),
	.A2(n11),
	.A1(accumulator[2]));
   AN2D0 C62 (.Z(n55),
	.A2(n11),
	.A1(accumulator[3]));
   AN2D0 C61 (.Z(n54),
	.A2(n11),
	.A1(accumulator[4]));
   AN2D0 C60 (.Z(n53),
	.A2(n11),
	.A1(accumulator[5]));
   AN2D0 C59 (.Z(n52),
	.A2(n11),
	.A1(accumulator[6]));
   AN2D0 C58 (.Z(n51),
	.A2(n11),
	.A1(accumulator[7]));
   OR2D0 C56 (.Z(n49),
	.A2(sample_clk),
	.A1(counter[0]));
   AN2D0 C55 (.Z(n48),
	.A2(n68),
	.A1(counter[1]));
   OR2D0 C54 (.Z(n47),
	.A2(sample_clk),
	.A1(counter[2]));
   AN2D0 C53 (.Z(n46),
	.A2(n68),
	.A1(counter[3]));
   AN2D0 C52 (.Z(n45),
	.A2(n68),
	.A1(counter[4]));
   AN2D0 C51 (.Z(n44),
	.A2(n68),
	.A1(counter[5]));
   AN2D0 C50 (.Z(n43),
	.A2(n68),
	.A1(counter[6]));
   AN2D0 C49 (.Z(n42),
	.A2(n68),
	.A1(counter[7]));
   AN2D0 C48 (.Z(n41),
	.A2(n68),
	.A1(counter[8]));
   AN2D0 C47 (.Z(n40),
	.A2(n68),
	.A1(counter[9]));
   AN2D0 C46 (.Z(n39),
	.A2(n68),
	.A1(counter[10]));
   AN2D0 C45 (.Z(n38),
	.A2(n68),
	.A1(counter[11]));
   AN2D0 C44 (.Z(n37),
	.A2(n68),
	.A1(counter[12]));
   AN2D0 C43 (.Z(n36),
	.A2(n68),
	.A1(counter[13]));
   AN2D0 C42 (.Z(n35),
	.A2(n68),
	.A1(counter[14]));
   AN2D0 C41 (.Z(n34),
	.A2(n68),
	.A1(counter[15]));
   AN2D0 C40 (.Z(n33),
	.A2(n68),
	.A1(counter[16]));
   AN2D0 C39 (.Z(n32),
	.A2(n68),
	.A1(counter[17]));
   AN2D0 C38 (.Z(n31),
	.A2(n68),
	.A1(counter[18]));
   AN2D0 C37 (.Z(n30),
	.A2(n68),
	.A1(counter[19]));
   AN2D0 C36 (.Z(n29),
	.A2(n68),
	.A1(counter[20]));
   AN2D0 C35 (.Z(n28),
	.A2(n68),
	.A1(counter[21]));
   AN2D0 C34 (.Z(n27),
	.A2(n68),
	.A1(counter[22]));
   AN2D0 C33 (.Z(n26),
	.A2(n68),
	.A1(counter[23]));
   AN2D0 C32 (.Z(n25),
	.A2(n68),
	.A1(counter[24]));
   AN2D0 C31 (.Z(n24),
	.A2(n68),
	.A1(counter[25]));
   AN2D0 C30 (.Z(n23),
	.A2(n68),
	.A1(counter[26]));
   AN2D0 C29 (.Z(n22),
	.A2(n68),
	.A1(counter[27]));
   AN2D0 C28 (.Z(n17),
	.A2(n68),
	.A1(counter[28]));
   AN2D0 C27 (.Z(n6),
	.A2(n68),
	.A1(counter[29]));
   AN2D0 C26 (.Z(n5),
	.A2(n68),
	.A1(counter[30]));
   AN2D0 C25 (.Z(n4),
	.A2(n68),
	.A1(counter[31]));
   DFCNQD1 \accumulator_reg[7]  (.Q(accumulator[7]),
	.D(N111),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[6]  (.Q(accumulator[6]),
	.D(N110),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[5]  (.Q(accumulator[5]),
	.D(N109),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[4]  (.Q(accumulator[4]),
	.D(N108),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[3]  (.Q(accumulator[3]),
	.D(N107),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[2]  (.Q(accumulator[2]),
	.D(N106),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[1]  (.Q(accumulator[1]),
	.D(N105),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \accumulator_reg[0]  (.Q(accumulator[0]),
	.D(N104),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[16]  (.Q(counter[16]),
	.D(N57),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[23]  (.Q(counter[23]),
	.D(N64),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[27]  (.Q(counter[27]),
	.D(N68),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[31]  (.Q(counter[31]),
	.D(N72),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[15]  (.Q(counter[15]),
	.D(N56),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[19]  (.Q(counter[19]),
	.D(N60),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[22]  (.Q(counter[22]),
	.D(N63),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[26]  (.Q(counter[26]),
	.D(N67),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[30]  (.Q(counter[30]),
	.D(N71),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[18]  (.Q(counter[18]),
	.D(N59),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[21]  (.Q(counter[21]),
	.D(N62),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[25]  (.Q(counter[25]),
	.D(N66),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[29]  (.Q(counter[29]),
	.D(N70),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[17]  (.Q(counter[17]),
	.D(N58),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[20]  (.Q(counter[20]),
	.D(N61),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[24]  (.Q(counter[24]),
	.D(N65),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[28]  (.Q(counter[28]),
	.D(N69),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \coef_addr_wire_reg[2]  (.Q(coef_addr[2]),
	.D(N114),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \coef_addr_wire_reg[1]  (.Q(coef_addr[1]),
	.D(N113),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \coef_addr_wire_reg[0]  (.Q(coef_addr[0]),
	.D(N112),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[6]  (.Q(counter[6]),
	.D(N47),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[12]  (.Q(counter[12]),
	.D(N53),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[9]  (.Q(counter[9]),
	.D(N50),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[8]  (.Q(counter[8]),
	.D(N49),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[14]  (.Q(counter[14]),
	.D(N55),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[7]  (.Q(counter[7]),
	.D(N48),
	.CP(clk__L4_N2),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[13]  (.Q(counter[13]),
	.D(N54),
	.CP(clk__L4_N0),
	.CDN(rst_n));
   DFCNQD1 CURRENT_STATE_reg (.Q(CURRENT_STATE),
	.D(NEXT_STATE),
	.CP(clk__L4_N1),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[10]  (.Q(counter[10]),
	.D(N51),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[11]  (.Q(counter[11]),
	.D(N52),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[1]  (.Q(counter[1]),
	.D(N42),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[5]  (.Q(counter[5]),
	.D(N46),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[4]  (.Q(counter[4]),
	.D(N45),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFCNQD1 \counter_reg[3]  (.Q(counter[3]),
	.D(N44),
	.CP(clk__L4_N3),
	.CDN(rst_n));
   DFSND1 \counter_reg[0]  (.SDN(rst_n),
	.QN(n2),
	.Q(counter[0]),
	.D(N41),
	.CP(clk__L4_N3));
   DFSND1 \counter_reg[2]  (.SDN(rst_n),
	.QN(n1),
	.Q(counter[2]),
	.D(N43),
	.CP(clk__L4_N3));
   DFSND1 dav_wire_reg (.SDN(rst_n),
	.Q(dav),
	.D(n72),
	.CP(clk__L4_N1));
   DFCNQD1 \outp_wire_reg[3]  (.Q(outp[3]),
	.D(accumulator[3]),
	.CP(net80),
	.CDN(rst_n));
   DFCNQD1 \outp_wire_reg[2]  (.Q(outp[2]),
	.D(accumulator[2]),
	.CP(net80),
	.CDN(rst_n));
   DFCNQD1 \outp_wire_reg[1]  (.Q(outp[1]),
	.D(accumulator[1]),
	.CP(net80),
	.CDN(rst_n));
   DFCNQD1 \outp_wire_reg[0]  (.Q(outp[0]),
	.D(accumulator[0]),
	.CP(net80),
	.CDN(rst_n));
   INVD1 U4 (.ZN(n68),
	.I(sample_clk));
   AN2D0 U6 (.Z(N70),
	.A2(n68),
	.A1(N38));
   AN2D0 U7 (.Z(N68),
	.A2(n68),
	.A1(N36));
   AN2D0 U8 (.Z(N71),
	.A2(n68),
	.A1(N39));
   AN2D0 U9 (.Z(N69),
	.A2(n68),
	.A1(N37));
   AN2D0 U10 (.Z(N67),
	.A2(n68),
	.A1(N35));
   AN2D0 U11 (.Z(N66),
	.A2(n68),
	.A1(N34));
   AN2D0 U12 (.Z(N65),
	.A2(n68),
	.A1(N33));
   AN2D0 U13 (.Z(N64),
	.A2(n68),
	.A1(N32));
   AN2D0 U14 (.Z(N63),
	.A2(n68),
	.A1(N31));
   AN2D0 U15 (.Z(N62),
	.A2(n68),
	.A1(N30));
   AN2D0 U16 (.Z(N61),
	.A2(n68),
	.A1(N29));
   AN2D0 U17 (.Z(N60),
	.A2(n68),
	.A1(N28));
   AN2D0 U18 (.Z(N59),
	.A2(n68),
	.A1(N27));
   AN2D0 U19 (.Z(N58),
	.A2(n68),
	.A1(N26));
   AN2D0 U20 (.Z(N57),
	.A2(n68),
	.A1(N25));
   INVD1 U21 (.ZN(n71),
	.I(n11));
   AN2D0 U22 (.Z(N54),
	.A2(n68),
	.A1(N22));
   AN2D0 U23 (.Z(N50),
	.A2(n68),
	.A1(N18));
   AN2D0 U24 (.Z(N104),
	.A2(n11),
	.A1(N85));
   AN2D0 U25 (.Z(N105),
	.A2(n11),
	.A1(N86));
   AN2D0 U26 (.Z(N106),
	.A2(n11),
	.A1(N87));
   AN2D0 U27 (.Z(N107),
	.A2(n11),
	.A1(N88));
   AN2D0 U28 (.Z(N108),
	.A2(n11),
	.A1(N89));
   AN2D0 U29 (.Z(N109),
	.A2(n11),
	.A1(N90));
   AN2D0 U30 (.Z(N110),
	.A2(n11),
	.A1(N91));
   AN2D0 U31 (.Z(N53),
	.A2(n68),
	.A1(N21));
   AN2D0 U32 (.Z(N51),
	.A2(n68),
	.A1(N19));
   AN2D0 U33 (.Z(N49),
	.A2(n68),
	.A1(N17));
   AN2D0 U34 (.Z(N56),
	.A2(n68),
	.A1(N24));
   AN2D0 U35 (.Z(N55),
	.A2(n68),
	.A1(N23));
   AN2D0 U36 (.Z(N52),
	.A2(n68),
	.A1(N20));
   AN2D0 U37 (.Z(N48),
	.A2(n68),
	.A1(N16));
   AN2D0 U38 (.Z(N42),
	.A2(n68),
	.A1(N10));
   IND2D1 U40 (.ZN(N43),
	.B1(n68),
	.A1(N11));
   AN2D0 U41 (.Z(N47),
	.A2(n68),
	.A1(N15));
   AN2D0 U42 (.Z(N46),
	.A2(n68),
	.A1(N14));
   AN2D0 U43 (.Z(N45),
	.A2(n68),
	.A1(N13));
   AN2D0 U44 (.Z(N44),
	.A2(n68),
	.A1(N12));
   IND2D1 U45 (.ZN(N41),
	.B1(n68),
	.A1(N9));
   AN2D0 U47 (.Z(N72),
	.A2(n68),
	.A1(N40));
   INVD1 U48 (.ZN(n72),
	.I(CURRENT_STATE));
   IAO21D1 U49 (.ZN(n11),
	.B(n72),
	.A2(n1),
	.A1(n8));
   NR4D0 U50 (.ZN(n18),
	.A4(counter[23]),
	.A3(counter[24]),
	.A2(counter[25]),
	.A1(counter[26]));
   NR4D0 U51 (.ZN(n21),
	.A4(counter[6]),
	.A3(counter[7]),
	.A2(counter[8]),
	.A1(counter[9]));
   NR4D0 U52 (.ZN(n20),
	.A4(counter[31]),
	.A3(counter[3]),
	.A2(counter[4]),
	.A1(counter[5]));
   NR4D0 U53 (.ZN(n19),
	.A4(counter[27]),
	.A3(counter[28]),
	.A2(counter[29]),
	.A1(counter[30]));
   NR4D0 U54 (.ZN(n15),
	.A4(counter[10]),
	.A3(counter[11]),
	.A2(n3),
	.A1(n2));
   OR4D1 U55 (.Z(n3),
	.A4(counter[12]),
	.A3(counter[13]),
	.A2(counter[14]),
	.A1(counter[15]));
   IND4D1 U56 (.ZN(n8),
	.B3(n16),
	.B2(n15),
	.B1(n14),
	.A1(n13));
   NR4D0 U57 (.ZN(n16),
	.A4(counter[16]),
	.A3(counter[17]),
	.A2(counter[18]),
	.A1(counter[19]));
   NR4D0 U58 (.ZN(n14),
	.A4(counter[1]),
	.A3(counter[20]),
	.A2(counter[21]),
	.A1(counter[22]));
   ND4D1 U59 (.ZN(n13),
	.A4(n21),
	.A3(n20),
	.A2(n19),
	.A1(n18));
   AN2D0 U60 (.Z(N111),
	.A2(n11),
	.A1(N92));
   OAI22D0 U61 (.ZN(NEXT_STATE),
	.B2(n7),
	.B1(n72),
	.A2(n68),
	.A1(CURRENT_STATE));
   NR2D1 U62 (.ZN(n7),
	.A2(n8),
	.A1(counter[2]));
   NR2D1 U63 (.ZN(N112),
	.A2(coef_addr[0]),
	.A1(n71));
   OAI21D0 U64 (.ZN(N114),
	.B(n10),
	.A2(n73),
	.A1(n9));
   ND4D1 U65 (.ZN(n10),
	.A4(n73),
	.A3(n11),
	.A2(coef_addr[0]),
	.A1(coef_addr[1]));
   INVD1 U66 (.ZN(n73),
	.I(coef_addr[2]));
   NR2D1 U67 (.ZN(N113),
	.A2(n71),
	.A1(n12));
   XNR2D1 U68 (.ZN(n12),
	.A2(coef_addr[0]),
	.A1(coef_addr[1]));
endmodule

module ROM_Process (
	address, 
	coeficient_out);
   input [2:0] address;
   output [3:0] coeficient_out;

   // Internal wires
   wire \address[2] ;
   wire n1;
   wire n2;

   assign coeficient_out[3] = \address[2]  ;
   assign \address[2]  = address[2] ;

   NR2D1 U3 (.ZN(coeficient_out[2]),
	.A2(n1),
	.A1(coeficient_out[1]));
   AOI21D0 U4 (.ZN(coeficient_out[0]),
	.B(address[0]),
	.A2(n2),
	.A1(\address[2] ));
   INVD1 U5 (.ZN(n2),
	.I(address[1]));
   INVD1 U6 (.ZN(n1),
	.I(address[0]));
   XNR2D1 U7 (.ZN(coeficient_out[1]),
	.A2(n1),
	.A1(address[1]));
endmodule

module FIR_Toplevel_5 (
	rst_n, 
	clk, 
	sample_clk, 
	sample, 
	dav, 
	outp);
   input rst_n;
   input clk;
   input sample_clk;
   input [3:0] sample;
   output dav;
   output [3:0] outp;

   // Internal wires
   wire clk__L4_N3;
   wire clk__L4_N2;
   wire clk__L4_N1;
   wire clk__L4_N0;
   wire clk__L3_N0;
   wire clk__L2_N0;
   wire clk__L1_N0;
   wire [3:0] sample_out_wire;
   wire [3:0] coeficient_out_wire;
   wire [2:0] coef_addr_wire;

   CKND24 clk__L4_I3 (.CN(clk__L4_N3),
	.CLK(clk__L3_N0));
   CKND24 clk__L4_I2 (.CN(clk__L4_N2),
	.CLK(clk__L3_N0));
   CKND24 clk__L4_I1 (.CN(clk__L4_N1),
	.CLK(clk__L3_N0));
   CKND24 clk__L4_I0 (.CN(clk__L4_N0),
	.CLK(clk__L3_N0));
   CKND8 clk__L3_I0 (.CN(clk__L3_N0),
	.CLK(clk__L2_N0));
   CKND16 clk__L2_I0 (.CN(clk__L2_N0),
	.CLK(clk__L1_N0));
   CKND24 clk__L1_I0 (.CN(clk__L1_N0),
	.CLK(clk));
   Delayline_CB U_delayline (.rst_n(rst_n),
	.clk(clk__L2_N0),
	.sample_clk(sample_clk),
	.sample(sample),
	.sample_out(sample_out_wire),
	.clk__L4_N0(clk__L4_N0),
	.clk__L4_N1(clk__L4_N1),
	.clk__L4_N2(clk__L4_N2));
   FIR_Processor u_FIRP (.rst_n(rst_n),
	.clk(clk__L2_N0),
	.sample_clk(sample_clk),
	.sample_delay_in(sample_out_wire),
	.coeficient(coeficient_out_wire),
	.coef_addr(coef_addr_wire),
	.dav(dav),
	.outp(outp),
	.clk__L4_N0(clk__L4_N0),
	.clk__L4_N1(clk__L4_N1),
	.clk__L4_N2(clk__L4_N2),
	.clk__L4_N3(clk__L4_N3));
   ROM_Process u_ROM (.address(coef_addr_wire),
	.coeficient_out(coeficient_out_wire));
endmodule

